// <auto-generated />
namespace Way2Buy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EfDbContext1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EfDbContext1));
        
        string IMigrationMetadata.Id
        {
            get { return "201902280628319_EfDbContext1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
